version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: topsecretpw
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: secretpw
      MYSQL_DATABASE: trello
  api:
    image: trello:0.0.2
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: secretpw
      MYSQL_DATABASE: trello
      MYSQL_PORT: 3306
    depends_on:
      - db
